name: Deploy Pages

# 触发条件，push到main分支或者pull request到main分支
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# 设置时区
env:
  TZ: Asia/Shanghai

# 定义执行任务
jobs:
  # 构建任务
  build:
    # 使用最新版ubuntu
    runs-on: ubuntu-latest

    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3

      # 设置使用 Node.js 版本
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

        # 安装依赖
      - name: Install dependencies
        run: npm install

        # 构建项目
      - name: Build blog project
        run: npm run docs:build

      # 部署到 GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.vitepress/dist/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
